### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by mikebarkmin** [mikebarkmin/gestyled#1]
Unfortunately this project was stale for a long time. The dependencies are very old and need to be updated.

Be sure sure to test `yarn build` and `yarn:styleguide`.

**Comment by trblackw** [comment]
I'll take care of this 🙋🏻‍♂️ Please assign me

**Comment by eliamartani** [comment]
I did it too however styleguidist have some breaking changes causing the documentation to fail in some cases.

For example you'll get `Paper is not defined` in a lot of markdown files. Can't find a resolution for that yet.
